server:
  port: 8001

#mybatis配置
mybatis:
  type-aliases-package: com.fan.springcloud.pojo.Dept
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


#spring的配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #数据源
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456


#Eureka配置 服务注册到哪里
eureka:
  instance:
#    eureka.instance-id: springcloud-provider-dept8001  #修改eureka上的默认描述信息
    prefer-ip-address: true #使用ip地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #指定服务的id
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

#info配置
info:
  app.name: fan-springcloud
  company.name: fan.com
